ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_A_U35_MwScheme_UFO_v2_1'
     $ //'-cHe_massless'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_233 = ', GC_233
      WRITE(*,2) 'GC_234 = ', GC_234
      WRITE(*,2) 'GC_236 = ', GC_236
      WRITE(*,2) 'GC_248 = ', GC_248
      WRITE(*,2) 'GC_249 = ', GC_249
      WRITE(*,2) 'GC_254 = ', GC_254
      WRITE(*,2) 'GC_336 = ', GC_336
